version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_USER: newdevadmin
      POSTGRES_PASSWORD: 40S4r3dder
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: arianlearning@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 40S4r3dder
    ports:
      - '5050:80'

volumes:
  db:
    driver: local
